-- ERROR HANDLER
USE sqlDB;
DROP PROCEDURE IF EXISTS errorProc;
DELIMITER $$
CREATE PROCEDURE errorProc()
BEGIN
	DECLARE CONTINUE HANDLER FOR 1146 SELECT '테이블이 없습니다.' AS '메시지';
	SELECT * FROM noTable;
END $$
DELIMITER ; 
CALL errorProc();

-- ERROR SQLEXCEPTION
DROP PROCEDURE IF EXISTS errorProc2;
DELIMITER $$
CREATE PROCEDURE errorProc2()
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		SHOW ERRORS;
		SELECT '오류가 발생하여 작업을 취소하였습니다.' AS '메시지';
		ROLLBACK;
	END;
	INSERT INTO userTbl VALUES('LSG', '이상구', 1988, '서울', NULL, NULL, 170, CURRENT_DATE());
END $$
DELIMITER ;
CALL errorProc2();

-- PREPARE DEALLOCATE
USE sqlDB;
PREPARE myQuery FROM 'SELECT * FROM userTbl WHERE userID = "EJW"';
EXECUTE myQuery;
DEALLOCATE PREPARE myQuery;

-- PREPARE EXCUTE USING DEALLOCATE
DROP TABLE IF EXISTS myTable;
CREATE TABLE myTable (id INT AUTO_INCREMENT PRIMARY KEY, mDate DATETIME);

SET @curDATE = CURRENT_TIMESTAMP();

PREPARE myQuery FROM 'INSERT INTO myTable VALUES(NULL, ?)';
EXECUTE myQuery USING @curDATE;
DEALLOCATE PREPARE myQuery;

SELECT * FROM myTable;
